services:
  back:
    build: ./server
    container_name: back
    ports:
      - "3700:3700"
    volumes:
      - "./server/:/app"  
      - "/app/node_modules"
    command: npm start 
    environment:
      MONGO_URI: mongodb://ismahen:ismahen@dbMongo:27017 
  front:
    build: ./client
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/app"  
      - "/app/node_modules" 
    command: npm start      
    
  dbMongo: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ismahen
      MONGO_INITDB_ROOT_PASSWORD: ismahen
    volumes:
      - db-data:/data/db
volumes:
  db-data: {}        